### ISSUE TITLE
Add example showing bounds feature

### ISSUE THREAD

**Issue by teubert** [nasa/prog_models#116]
Add an example showing the new bounds feature. 

For example: Could be ThrownObject where position is limited by the ground.

Definition of Done:
- [ ] Add example (with notes as comments)
- [x] Add to examples/__init__.py
- [x] Add to examples tests
- [ ] Add to getting started documentation
- [x] Update release note documentation to reference example

**Comment by wlamberson1** [comment]
What are the notes you refer to in the first bullet point?

**Comment by teubert** [comment]
> @teubert What are the notes you refer to in the first bullet point?

Just in general I want the example to include comments describing what is done in each step and why- similar to the other examples

**Comment by wlamberson1** [comment]
I am not sure how to add state_limits_example to the downloads file in order to add it to the getting started documentation. How do I do this?
