### ISSUE TITLE
Progress Bar

### ISSUE THREAD

**Issue by teubert** [nasa/prog_models#117]
Add option to show progress bar in simulation. Uses @matteocorbetta's class

## DoD
 - [x] Implement
 - [x] Add documentation
 - [x] Added to example
 - [x] Added to requirements.txt and setup.py

**Comment by teubert** [comment]
Note: this adds a dependency. Add the dependency to requirements.txt and setup.py files. 

Also, I would want this disabled by default, and enabled by keyword argument

**Comment by lawrence-hwang** [comment]
`class ProgressBar():
def __init__(self, n, prefix='', suffix='', decimals=1, print_length=100, fill='█', print_end = " ") -> None:
self.n = n
self.prefix = prefix
self.suffix = suffix
self.decimals = decimals
self.print_length = print_length
self.fill = fill
self.print_end = print_end
pass

def __call__(self, iteration):
percent = ("{0:." + str(self.decimals) + "f}").format(100 * (iteration / float(self.n)))
filledLength = int(self.print_length * iteration // self.n)
bar = self.fill * filledLength + '-' * (self.print_length - filledLength)
print('\r%s |%s| %s%% %s' % (self.prefix, bar, percent, self.suffix), end = self.print_end)
# Print New Line on Complete
if iteration == self.n:
print('')`

**Comment by lawrence-hwang** [comment]
[Yesterday 2:34 PM] Corbetta, Matteo (ARC-TI)[KBR Wyle Services, LLC]
    classProgressBar():
def__init__(self, n, prefix='', suffix='', decimals=1, print_length=100, fill='█', print_end = " ") -> None:
self.n = n
self.prefix = prefix
self.suffix = suffix
self.decimals = decimals
self.print_length = print_length
self.fill = fill
self.print_end = print_end
pass
def__call__(self, iteration):
percent = ("{​​​0:." + str(self.decimals) + "f}​​​").format(100 * (iteration / float(self.n)))
filledLength = int(self.print_length * iteration // self.n)
bar = self.fill * filledLength + '-' * (self.print_length - filledLength)
print('\r%s |%s| %s%%%s' % (self.prefix, bar, percent, self.suffix), end = self.print_end)
# Print New Line on Complete
ifiteration == self.n:
print('')
