### ISSUE TITLE
Add tutorial to docs

### ISSUE THREAD

**Issue by teubert** [nasa/prog_models#138]
Update docs to send users to tutorial juypter notebook. I want to make it obvious, some way of making sure users get there first. Current thinking is as a large text link and badge on documentation home page (and readme), a badge on getting started, and a option in the side navigation menu, but I'll leave it up to whoever implements this to see what works the best. 

I was thinking of using binder instead of embedding the notebook text. Something like this: https://mybinder.org/v2/gh/nasa/prog_models/dev?labpath=tutorial.ipynb. Note: binder can automatically generate badges. See: https://mybinder.org

----------
Previous Text:
Tools exist to add jupyter notebooks to sphinx doc (see https://blog.jupyter.org/integrating-output-in-documentation-with-jupyter-sphinx-ecf569ddab85, https://nbsphinx.readthedocs.io/en/0.8.7/). 

I would like to setup sphinx to include the tutorial as it's own page.

**Comment by teubert** [comment]
Thank you @anonymousr007! I appreciate your help

If you're interested, I would like to make the same change to nasa/prog_algs as well (see https://github.com/nasa/prog_algs/issues/86)

**Comment by anonymousr007** [comment]
> Thank you @anonymousr007! I appreciate your help
> 
> If you're interested, I would like to make the same change to nasa/prog_algs as well (see [nasa/prog_algs#86](https://github.com/nasa/prog_algs/issues/86))

Yeah, I'll do it and we are contributor in prog_models 🎉
