### ISSUE TITLE
Extend tests for SimResult

### ISSUE THREAD

**Issue by teubert** [nasa/prog_models#151]
Sim result now includes methods for extend, index, remove, etc. make sure those are adequately tested

**Comment by SauravMaheshkar** [comment]
Hey @teubert 👋, aren't tests for `SimResult` and `LazySimResult` already present in [**`test_sim_result.py`**](https://github.com/nasa/prog_models/blob/master/tests/test_sim_result.py) ? At least indexing is tested right ?

https://github.com/nasa/prog_models/blob/8f9636ee3f44d699172eda54acd32fca2df518d3/tests/test_sim_result.py#L6

**Comment by teubert** [comment]
Hi @SauravMaheshkar, Somehow I missed your message. Yes, some features of sim result were tested, this action was to extend those tests to be more complete. Thanks for your question
