### ISSUE TITLE
Fix slow import

### ISSUE THREAD

**Issue by teubert** [nasa/prog_models#26]
import prog_models is really slow. Look for ways to speed it up

**Comment by Samad999777** [comment]
@teubert Can you highlight in which case it is slow? in the examples or in general ?

**Comment by teubert** [comment]
@Samad999777  In a general sense. Import prog_models is slower than I want it to be.

**Comment by Samad999777** [comment]
@teubert  Alright, I will take a look at it, maybe we have some duplicate imports in the packages
