### ISSUE TITLE
Add derived param feature example and to tutorial

### ISSUE THREAD

**Issue by teubert** [nasa/prog_models#39]
**Background**
#30 introduced a new feature- derived model configuration parameters. Derived parameters are automatically calculated as their dependencies are updated. So if there is a derived parameter 'c' that is defined as param['b'] * param['a'], the update function for c is triggered whenever a or b is updated.

## Definition of Done
In order to help users use this feature, this task is to create an example with a model that uses derived parameters. My initial thought is to update the simple thrown object model to make throwing speed a function of thrower height. For this issue to be complete the following things must be done:
- [ ] Create a new example that simply illustrates how to use derived parameters 
- [ ] Update getting_started sphinx config to include the new example
- [ ] Add to the tutorial a simple example of derived parameter

**Comment by Samad999777** [comment]
Hey @teubert, are you open to letting me contribute to this? and also can you write some details regarding it. Thanks

**Comment by teubert** [comment]
Hello @Samad999777, 

100% yes! To contribute to the repository you first need to complete the Contributor agreement from https://github.com/nasa/prog_models/tree/master/forms and email it to christopher.a.teubert@nasa.gov. Once you do that I can add you as an approved contributor. 

And yes, I'll add some additional details to the issue. 

Thank you for your interest in contributing!

**Comment by Samad999777** [comment]
Hey @teubert thanks for your quick response, Can I sign the agreement digitally or do I need to put in my physical signatures ?

**Comment by teubert** [comment]
@Samad999777 I think digital signature is fine.

**Comment by Samad999777** [comment]
@teubert I have emailed it to you :)
