### ISSUE TITLE
insufficient check for file type

### ISSUE THREAD

**Issue by snoyes** [nasa/prog_models#390]
https://github.com/nasa/prog_models/blob/103b6c388ac00edbcf6631c98872a53898947dfe/scripts/test_copyright.py#L17

Checking that the last two characters are 'py' is not sufficient for finding Python files.

Other extensions may end in 'py'. For example, the concept-tagging-api repository includes some '.npy' files, which are NumPy data files. They will not have the license line.

Python files might not end in 'py'. For example, the EMTG repository includes a '.pyw' file, which is used in Windows to prevent opening a new terminal window.

If reliance on extensions is sufficient, I recommend something like `and path.split(".")[-1] in ("py", "pyw", "py3", "ipynb")`

**Comment by teubert** [comment]
Thank you @snoyes- good catch. Currently we don't have any .pyw or .py3 files, but I could see this becoming an issue in the future. 

If you have time- could you provide a review for the PR fixing this: #391?
