### ISSUE TITLE
SimResult 

### ISSUE THREAD

**Issue by teubert** [nasa/prog_models#95]
Fix returned result of sim to, ideally perform the following:
1. Correlate time to value 
2. simplify plotting 
3. Extendable to include observables, thresholds_met
4. Only calculate derived values as needed (for efficiency)
5. Must be backwards compatible

Definition of done:
- [ ] Implement SimResult Class
- [ ] Update examples, tutorial to use it 
- [ ] Add tests of SimResult 
- [ ] Add to release notes

**Comment by teubert** [comment]
I see two options:

1. Single object returned, which contains model, times, states, and will allow access to outputs, event_states, etc. on request (and calculates first time). This class could be unpacked to maintain backwards compatibility (using __iter__). This meets all our goals. Example of use:
`python 
simulate_to_threshold():
  ...
  return SimResult(model, times, states)
(times, inputs, states, outputs, event_states) = m.simulate_to_threshold() # Can be unpacked for backwards compatibility
result = m.simulate_to_threshold() #Ideal use
times = result.times
print(result.times[10])
print(result.outputs[50]) # Calculated on first request
visualize.plot(result.times, result.states)
`
2. Each array (output, states, etc) is a SimResult correlating time and value. Outputs, etc. would be calculated on first request. Example of use:
`python 
(times, inputs, states, outputs, event_states) = m.simulate_to_threshold() 
times = inputs.times # Can also be accessed like this 
print(outputs.times[10])
print(outputs[50]) # Calculated on first request
outputs.plot() # This would be nicer
`

@jason-watkins, @wlamberson1 : What are your thoughts on these two approaches?

**Comment by jason-watkins** [comment]
I don't see any reason why each of the various outputs would have a different set of times from the others, so I think the first option, which avoids duplicating the times is preferable.
